name: objectbox_flutter
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Generate fake data
  faker: ^2.0.0

  # ObjectBox
  objectbox: ^1.5.0

  ### USE ONE OF THE PACKAGES BELOW
  # objectbox_flutter_libs: any #1 only local database
  objectbox_sync_flutter_libs: any #2 both local + server

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  # ObjectBox
  build_runner: ^2.1.11
  objectbox_generator: any

flutter:
  uses-material-design: true